package com.myspace.script_test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HelloServices implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public HelloServices() {
    }




}